version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spattle_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - spattle_dev_network

volumes:
  mysql_dev_data:

networks:
  spattle_dev_network:
    driver: bridge
